// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMV-txe3yjNt6UeIKDNO6EEVK1XVYb6MI',
    appId: '1:269471985170:web:988a778a885dca3ac5f2cb',
    messagingSenderId: '269471985170',
    projectId: 'moneymate-student',
    authDomain: 'moneymate-student.firebaseapp.com',
    storageBucket: 'moneymate-student.firebasestorage.app',
    measurementId: 'G-4XJV92C2FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClGfzWcR7Bkmfy5v4D4JBfzl44TTq1Twg',
    appId: '1:269471985170:android:4d9a0ff8b10425bdc5f2cb',
    messagingSenderId: '269471985170',
    projectId: 'moneymate-student',
    storageBucket: 'moneymate-student.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKAZIS2XaJJmTrgDdoZWGxBaxoIPXJKCU',
    appId: '1:269471985170:ios:b7caf6d59e1e97a1c5f2cb',
    messagingSenderId: '269471985170',
    projectId: 'moneymate-student',
    storageBucket: 'moneymate-student.firebasestorage.app',
    iosBundleId: 'com.example.moneymateStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKAZIS2XaJJmTrgDdoZWGxBaxoIPXJKCU',
    appId: '1:269471985170:ios:b7caf6d59e1e97a1c5f2cb',
    messagingSenderId: '269471985170',
    projectId: 'moneymate-student',
    storageBucket: 'moneymate-student.firebasestorage.app',
    iosBundleId: 'com.example.moneymateStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMV-txe3yjNt6UeIKDNO6EEVK1XVYb6MI',
    appId: '1:269471985170:web:0f7d2dd8bced712ec5f2cb',
    messagingSenderId: '269471985170',
    projectId: 'moneymate-student',
    authDomain: 'moneymate-student.firebaseapp.com',
    storageBucket: 'moneymate-student.firebasestorage.app',
    measurementId: 'G-QKF2TT4HJK',
  );
}
